env:
  browser: true
  es6: true
extends: standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - '@emotion'
rules:
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  space-before-function-paren: [error, never]
  comma-dangle: [error, always-multiline]
  '@emotion/jsx-import': error
  '@emotion/pkg-renaming': error
  '@emotion/no-vanilla': error
  '@emotion/import-from-emotion': error
  '@emotion/styled-import': error
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    parser: '@typescript-eslint/parser'
    rules:
      no-useless-constructor: off
      no-unused-vars: off
      no-use-before-define: off
      brace-style: off
      '@typescript-eslint/no-useless-constructor': error
      '@typescript-eslint/no-unused-vars': error
      '@typescript-eslint/no-use-before-define': error
      '@typescript-eslint/brace-style': error
    settings:
      react:
        pragma: "React"
        version: "detect"
