env:
  browser: true
  es6: true
extends: standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint/eslint-plugin'
rules: {
  react/jsx-uses-react: error,
  react/jsx-uses-vars: error,
  space-before-function-paren: [error, never],
  comma-dangle: [error, always-multiline]
}
overrides:
  - files:
      '*.ts'
    parser: '@typescript-eslint/parser'
    rules:
      no-useless-constructor: 0
      '@typescript-eslint/no-useless-constructor': 2
