export declare const PRIMARY_COLORSET: Readonly<{
    CINNABAR: import("./color.class").Color;
    ROBINS_EGG_BLUE: import("./color.class").Color;
    SHAMROCK: import("./color.class").Color;
    SUNGLOW: import("./color.class").Color;
}>;
export declare const SECONDARY_COLORSET: Readonly<{
    AMETHYST: import("./color.class").Color;
    AQUA_HAZE: import("./color.class").Color;
    BLUE_LAGOON: import("./color.class").Color;
    CRUSTA: import("./color.class").Color;
    PARIS_DAISY: import("./color.class").Color;
    PICTON_BLUE: import("./color.class").Color;
}>;
export declare const FULL_COLORSET: Readonly<{
    ALTO: import("./color.class").Color;
    BITTERSWEET: import("./color.class").Color;
    BLACK_SQUEEZE: import("./color.class").Color;
    BLIZZARD_BLUE: import("./color.class").Color;
    BLUE_STONE: import("./color.class").Color;
    BOULDER: import("./color.class").Color;
    BOTTICELLI: import("./color.class").Color;
    BRANDY_PUNCH: import("./color.class").Color;
    BRIDESMAID: import("./color.class").Color;
    CHATHAMS_BLUE: import("./color.class").Color;
    EMINENCE: import("./color.class").Color;
    EMPEROR: import("./color.class").Color;
    FLORAL_WHITE: import("./color.class").Color;
    FRENCH_LILAC: import("./color.class").Color;
    ILLUSION: import("./color.class").Color;
    ISLAND_SPICE: import("./color.class").Color;
    JEWEL: import("./color.class").Color;
    LEMON_CHIFFON: import("./color.class").Color;
    LIGHT_APRICOT: import("./color.class").Color;
    LINEN: import("./color.class").Color;
    MAGIC_MINT: import("./color.class").Color;
    MINE_SHAFT: import("./color.class").Color;
    PEACH: import("./color.class").Color;
    RIPE_LEMON: import("./color.class").Color;
    SEASHELL: import("./color.class").Color;
    SILVER_CHALICE: import("./color.class").Color;
    TALL_POPPY: import("./color.class").Color;
    TIA_MARIA: import("./color.class").Color;
    SHERPA_BLUE: import("./color.class").Color;
    SAIL: import("./color.class").Color;
    SELAGO: import("./color.class").Color;
    SINBAD: import("./color.class").Color;
    SNUFF: import("./color.class").Color;
    WHITE_ICE: import("./color.class").Color;
    AMETHYST: import("./color.class").Color;
    AQUA_HAZE: import("./color.class").Color;
    BLUE_LAGOON: import("./color.class").Color;
    CRUSTA: import("./color.class").Color;
    PARIS_DAISY: import("./color.class").Color;
    PICTON_BLUE: import("./color.class").Color;
    CINNABAR: import("./color.class").Color;
    ROBINS_EGG_BLUE: import("./color.class").Color;
    SHAMROCK: import("./color.class").Color;
    SUNGLOW: import("./color.class").Color;
}>;
