import {
  R300_COLOR,
  R400_COLOR,
  T300_COLOR,
  G200_COLOR,
  Y300_COLOR,
  P400_COLOR,
  B400_COLOR,
  Y500_COLOR,
  T500_COLOR,
  B100_COLOR,
  Y100_COLOR,
} from './colors'

export const PRIMARY_COLORSET = Object.freeze({
  CINNABAR: R400_COLOR,
  ROBINS_EGG_BLUE: T300_COLOR,
  SHAMROCK: G200_COLOR,
  SUNGLOW: Y300_COLOR,
})

export const SECONDARY_COLORSET = Object.freeze({
  AMETHYST: P400_COLOR,
  PICTON_BLUE: B400_COLOR,
  CRUSTA: Y500_COLOR,
  BLUE_LAGOON: T500_COLOR,
  AQUA_HAZE: B100_COLOR,
  PARIS_DAISY: Y100_COLOR,
})

export const FULL_COLORSET = Object.freeze({
  ...PRIMARY_COLORSET,
  ...SECONDARY_COLORSET,
  BITTERSWEET: R300_COLOR,
})
