import {
  R300_COLOR,
  R400_COLOR,
  P400_COLOR,
  B400_COLOR,
  N500_COLOR,
  N400_COLOR,
  N300_COLOR,
  N200_COLOR,
  N100_COLOR,
  N75_COLOR,
  C200_COLOR,
  G400_COLOR,
  O200_COLOR,
  O300_COLOR,
  C300_COLOR,
  C25_COLOR,
  Y400_COLOR,
  R500_COLOR,
  R200_COLOR,
  R100_COLOR,
  C500_COLOR,
  C400_COLOR,
  C100_COLOR,
  C75_COLOR,
  C50_COLOR,
  C15_COLOR,
  B500_COLOR,
  B300_COLOR,
  B200_COLOR,
  G500_COLOR,
  G300_COLOR,
  G200_COLOR,
  Y500_COLOR,
  Y300_COLOR,
  Y200_COLOR,
  P500_COLOR,
  P300_COLOR,
  P200_COLOR,
  O500_COLOR,
  O400_COLOR,
  O100_COLOR,
  O75_COLOR,
  O50_COLOR,
  O25_COLOR,
} from './colors'

export const PRIMARY_COLORSET = Object.freeze({
  CINNABAR: R400_COLOR,
  ROBINS_EGG_BLUE: C200_COLOR,
  SHAMROCK: G400_COLOR,
  SUNGLOW: O200_COLOR,
})

export const SECONDARY_COLORSET = Object.freeze({
  AMETHYST: P400_COLOR,
  AQUA_HAZE: C25_COLOR,
  BLUE_LAGOON: C300_COLOR,
  CRUSTA: O300_COLOR,
  PARIS_DAISY: Y400_COLOR,
  PICTON_BLUE: B400_COLOR,
})

export const FULL_COLORSET = Object.freeze({
  ...PRIMARY_COLORSET,
  ...SECONDARY_COLORSET,
  ALTO: N100_COLOR,
  BITTERSWEET: R300_COLOR,
  BLACK_SQUEEZE: C15_COLOR,
  BLIZZARD_BLUE: C75_COLOR,
  BLUE_STONE: C400_COLOR,
  BOULDER: N300_COLOR,
  BOTTICELLI: C50_COLOR,
  BRANDY_PUNCH: O400_COLOR,
  BRIDESMAID: O50_COLOR,
  CHATHAMS_BLUE: B500_COLOR,
  EMINENCE: P500_COLOR,
  EMPEROR: N400_COLOR,
  FLORAL_WHITE: O25_COLOR,
  FRENCH_LILAC: P300_COLOR,
  ILLUSION: R200_COLOR,
  ISLAND_SPICE: Y200_COLOR,
  JEWEL: G500_COLOR,
  LEMON_CHIFFON: Y300_COLOR,
  LIGHT_APRICOT: O100_COLOR,
  LINEN: R100_COLOR,
  MAGIC_MINT: G300_COLOR,
  MINE_SHAFT: N500_COLOR,
  PEACH: O75_COLOR,
  RIPE_LEMON: Y500_COLOR,
  SEASHELL: N75_COLOR,
  SILVER_CHALICE: N200_COLOR,
  TALL_POPPY: R500_COLOR,
  TIA_MARIA: O500_COLOR,
  SHERPA_BLUE: C500_COLOR,
  SAIL: B300_COLOR,
  SELAGO: B200_COLOR,
  SINBAD: C100_COLOR,
  SNUFF: P200_COLOR,
  WHITE_ICE: G200_COLOR,
})

// TODO: use it to generate the sass file
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const FERPECTION_THEME_COLORSET = Object.freeze({
  BRAND: PRIMARY_COLORSET.CINNABAR, // brand

  POSITIVE: PRIMARY_COLORSET.SHAMROCK, // positive info
  POSITIVE_HOVER: '#20bf7e',
  POSITIVE_FOCUS: '#d8f8eb',
  POSITIVE_BACKGROUND: '#e9fbf4',

  NEGATIVE: PRIMARY_COLORSET.SUNGLOW, // negative info
  NEGATIVE_HOVER: '#fcb413',
  NEGATIVE_BACKGROUND: '#fffbf0',

  ACTION: PRIMARY_COLORSET.ROBINS_EGG_BLUE, // buttons and links
  ACTION_HOVER: '#00aab7', // hover of buttons and links
  ACTION_FOCUS: '#40d9e5',
  ACTION_BACKGROUND: FULL_COLORSET.BLACK_SQUEEZE,

  FOREGROUND: '#7b7b7b', // default copy
  BACKGROUND: FULL_COLORSET.ALTO, // default background

  GREY: FULL_COLORSET.SILVER_CHALICE,
  GREY_LIGHT: FULL_COLORSET.ALTO,
  GREY_EXTRALIGHT: FULL_COLORSET.SEASHELL,
})
