name: UiKit CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Use PNPM
      run: curl -L https://unpkg.com/@pnpm/self-installer | node
    - name: Install dependencies
      run: pnpm install --shamefully-hoist
    - name: Build package
      run: pnpm run build
    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v1
      with:
        version: ${{ github.ref }}
        path: ./CHANGELOG.md
    - run: echo ${{ steps.changelog_reader.outputs.log_entry }}
