name: UiKit CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: curl -L https://unpkg.com/@pnpm/self-installer | node
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm test
      env:
        CI: true
